routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'CalendarioController@index');

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/calendario', 'CalendarioController@index')->name('calendario');

// -------- USUARIOS ---------
Auth::routes();
Route::resource('users', 'UsersController');
Route::get('/users/buscar/{consulta}', 'UsersController@buscar')->name('users.buscar');

// ----- DIVISIONES -------
Route::resource('divisions', 'DivisionController');
Route::get('/divisions/buscar/{consulta}', 'DivisionController@buscar')->name('divisions.buscar');

// ------- DEPARTAMENTOS -------
Route::resource('divisions.departamentos', 'DivisionDepartamentoController');
Route::resource('departamentos', 'DepartamentosController');

// ------- ACADEMIAS --------
Route::resource('divisions.departamentos.academias', 'DivisionDepartamentoAcademiaController');
Route::get('/divisions/{division}/departamentos/{departamento}/academias/{academia}/miembros/agregar', 'DivisionDepartamentoAcademiaController@agregarMiembro')
        ->name('divisions.departamentos.academias.agregar-miembro');
Route::delete('/divisions/{division}/departamentos/{departamento}/academias/{academia}/miembros/{miembro}', 'DivisionDepartamentoAcademiaController@darDeBajaMiembro')
        ->name('divisions.departamentos.academias.darDeBajaMiembro');

// ------ REUNIONES -----------
Route::resource('academias.reuniones', 'AcademiaReunionesController')
        ->except(['store', 'update', 'destroy'])
        ->middleware('auth');
Route::resource('/reuniones', 'ReunionesController')
        ->except(['store', 'update', 'destroy']);
Route::get('/reuniones/{id}/orden-del-dia', 'ReunionesController@descargarOrdenDelDia')
        ->name('reuniones.ordendeldia.descargar');
Route::get('/reuniones/{id}/emailpreview', 'ReunionesController@emailPreview');
// Route::get('/reuniones/{reunion}/vista-previa-od', function (App\Reunion $reunion){
//     $pdf = PDF::loadView('reuniones.ordendeldia', ['reunion' => $reunion]);
//     return $pdf->stream();
//     // return view('reuniones.ordendeldia', compact('reunion'));
// });

// --------- MINUTAS --------------
Route::resource('reuniones.minuta', 'ReunionesMinutasController')
        ->only(['index', 'create']);
// Route::get('/reuniones/{reunion}/minuta/vista-previa/', function (App\Reunion $reunion){
//     $pdf = PDF::loadView('reuniones.pdf.minuta', ['reunion' => $reunion]);
//     return $pdf->stream();
// });

// Enviar comentarios
Route::resource('feedback', 'FeedbackController')->only(['create', 'store'])->middleware('auth');

// ----------- TEAPOT ----------
Route::get('/teapot/brew','TeapotController@brew')->name('teapot.brew');

// TEST
// Route::view('mailtest', function () {
//         $feedback = App\Feedback::find(1);
//         return new App\Mail\FeedbackMail($feedback);
// });

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password',
        'grado', 'nombre',
        'apellido_paterno', 'apellido_materno'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Buscar usuario
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $busqueda
     * @param int $num_resultados
     * 
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeBuscar($query, string $busqueda, int $limit)
    {
        // $connection = config('database.default');
        // $driver = config("database.connections.{$connection}.driver");
        // if ($driver == 'sqlite') {
        //     $query = $query->whereRaw("nombre || ' ' || apellido_paterno || ' ' || apellido_materno LIKE '%{$busqueda}%'")
        //                 ->orderBy('apellido_paterno')
        // } else {
            $query = $query->whereRaw("CONCAT(nombre, ' ', apellido_paterno, ' ', apellido_materno) LIKE '%{$busqueda}%'")
                        ->orderBy('apellido_paterno');
        // }
        return $limit ? $query->limit($limit) : $query;
    }

    /**
     * Genera un api_token único y guarda al usuario.
     *
     * @return bool
     */
    public function rollApiKey(){
        do{
           $this->api_token = str_random(80);
        }while($this->where('api_token', $this->api_token)->exists());
        $this->save();
        return true;
    }

    /**
     * Retorna true si el usuario es miembro actual de la $academia dada.
     *
     * @param App\Academia $academia
     * @return bool
     */
    public function esMiembroActual(Academia $academia)
    {
        if ($academia->miembrosActuales->isEmpty()) return false;
        return $academia->miembrosActuales->contains($this); // Checa si hay registros donde el miembro siga activo
    }

    /**
     * Retorna true si el usuario es administrador del sistema.
     *
     * @return bool
     */
    public function getEsAdminAttribute()
    {
        return $this->email == config('admin.email');
    }

    /**
     * Retorna el nombre completo (iniciando por nombre) del usuario.
     *
     * @return string
     */
    public function getNombreCompletoAttribute()
    {
        return "{$this->nombre} {$this->apellido_paterno} {$this->apellido_materno}";
    }

    /**
     * Retorna el nombre completo (iniciando por nombre) con grado académico del usuario.
     *
     * @return string
     */
    public function getGradoNombreCompletoAttribute()
    {
        return "{$this->grado} {$this->nombre} {$this->apellido_paterno} {$this->apellido_materno}";
    }

    /* --------  Relaciones con tablas de jerarquía de la FI --------------- */

    public function divisionesQueHaDirigido()
    {
        return $this->belongsToMany(Division::class, 'division_jefe',
                                    'jefe_id', 'division_id')
                    ->using(DetallesIngresoEgreso::class)
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getDivisionesQueDirigeAttribute()
    {
        return $this->divisionesQueHaDirigido()->wherePivot('fecha_egreso', '=', null)->get();
    }

    public function departamentosQueHaDirigido()
    {
        return $this->belongsToMany(Departamento::class, 'departamento_jefe',
                                        'jefe_id', 'departamento_id')
                    ->using(DetallesIngresoEgreso::class)
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getDepartamentosQueDirigeAttribute()
    {
        return $this->departamentosQueHaDirigido()->wherePivot('fecha_egreso', '=', null)->get();
    }

    public function academiasQueHaPresidido()
    {
        return $this->belongsToMany(Academia::class, 'academia_presidente',
                                        'presidente_id', 'academia_id')
                    ->using(DetallesIngresoEgreso::class)
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getAcademiasQuePresideAttribute()
    {
        return $this->academiasQueHaPresidido()->wherePivot('fecha_egreso', '=', null)->get();
    }

    public function academias()
    {
        return $this->belongsToMany(Academia::class, 'academia_miembro',
                                    'miembro_id', 'academia_id')
                    ->using(DetallesIngresoEgreso::class) // Tabla pivote
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getAcademiasComoMiembroActivoAttribute()
    {
        return $this->academias()->wherePivot('fecha_egreso', '=', null)->get();
    }

    /* --------  Relaciones con tablas de reuniones, acuerdos, etc --------------- */

    public function reunionesComoConvocado()
    {
        return $this->belongsToMany(Reunion::class, 
            'convocado_reunion', 'convocado_id', 'reunion_id')
            ->as('asistencia')
            ->withPivot('asistio');
    }

    public function reunionesComoInvitadoExterno()
    {
        return $this->belongsToMany(Reunion::class, 
            'invitado_reunion', 'invitado_id', 'reunion_id')
            ->as('asistencia')
            ->withPivot('asistio');
    }
    
    public function getReunionesComoPresidenteAttribute()
    {
        return Reunion::whereIn('academia_id', $this->academiasQuePreside->pluck('id'))->get();
    }
    
    public function getReunionesComoJefeDeDepartamentoAttribute()
    {
        return Reunion::whereIn('academia_id', // Consulta principal (reuniones de las academias)
                Academia::whereIn('departamento_id', // Subconsulta 1 (academias del departamento)
                                $this->departamentosQueDirige->pluck('id') 
                            )->get()->pluck('id')
                        )->get();
    }
    
    public function getReunionesComoJefeDeDivisionAttribute()
    {
        return Reunion::whereIn('academia_id', // Consulta principal (reuniones de las academias)
                Academia::whereIn('departamento_id', // Subconsulta 1 (academias de departamentos que dirige)
                    Departamento::whereIn('division_id', // Subconsulta 2 (departamentos de divisiones que dirige)
                        $this->divisionesQueDirige->pluck('id') 
                    )->get()->pluck('id')
                )->get()->pluck('id')
            )->get();
    }

    public function getReunionesAttribute()
    {
        // Union entre todas las consultas
        return $this->reunionesComoConvocado->merge(
            $this->reunionesComoInvitadoExterno->merge(
                $this->ReunionesComoPresidente->merge(
                    $this->reunionesComoJefeDeDepartamento->merge(
                        $this->reunionesComoJefeDeDivision
                    )
                )
            )
        );
    }

    public function acuerdos()
    {
        return $this->hasMany(Acuerdo::class, 'responsable_id', 'id');
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Http\Resources\UserResource;
use App\Http\Resources\AcademiasCollection;
use App\Http\Resources\ReunionResource;
use App\Notifications\AvisoUsuarioCreado;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $q = $request->input('q');
        $limit = $request->input('limit', 5);
        if( $q ){
            return Cache::remember("user.buscar?q={$q}&limit={$limit}", now()->addSeconds(30), function () use ($q, $limit){
                // Si la cadena a buscar es menor o igual a 2 caracteres, devuelve una colección vacia
                $users = strlen($q) > 2 ? User::buscar($q, $limit)->get() : collect([]);
                // Si no encuentra usuarios, devuelve un error 404
                return $users->isNotEmpty() ? UserResource::collection($users) : response(['message' => 'No se encontró ningún usuario con los criterios de búsqueda'], 404);
            });
        }
        return UserResource::collection(User::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', User::class);
        $data = request()->validate(
            [
                'email' => 'required|string|email|max:50|unique:users',
                'password' => 'required|string|min:6|confirmed',
                'grado' => 'required|max:8|string',
                'nombre' => 'required|max:50|string',
                'apellido_paterno' => 'required|max:50|string',
                'apellido_materno' => 'required|max:50|string'
            ]
        );
        $user = User::create($data);
        $user->rollApiKey();
        $user->notify(new AvisoUsuarioCreado(['rawPass' => $data['password']])); // Avisamos al usuario por correo

        return response([
            'usuario' => new UserResource($user),
            'message' => 'Usuario creado safisfactoriamente',
        ], 201);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $this->authorize('view', $user);
        return new UserResource($user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function academiasQueHaPresidido(Request $request, int $user_id)
    {
        $user = User::findOrFail($user_id);
        $actual = $request->input('actual');
        if($actual && ($actual=="true" || $actual==1))
            // return new AcademiasCollection($user->academiasQueHaPresidido()->orderBy('nombre')->wherePivot('fecha_egreso', '=', null)->get());
            return new AcademiasCollection($user->academiasQuePreside->sortBy('nombre'));
        return new AcademiasCollection($user->academiasQueHaPresidido->sortBy('nombre'));
    }

    public function yo(Request $request)
    {
        // return json_encode(['mensaje'=> 'yo mero :D']);
        return new UserResource(Auth::user());
    }

    public function reuniones(int $user_id)
    {
        return ReunionResource::collection(User::findOrFail($user_id)->reuniones);
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('page-scripts')
    <script src="{{ asset('js/warn-exit.js') }}" defer></script>
@endsection

@section('title')
    Registrar Usuario
@endsection

@section('content')
    <form class="form-horizontal" method="POST" action="{{ route('users.index') }}">
        @csrf
        <div class="form-group row">
            <label for="grado" class="col-md-4 col-form-label text-md-right">
                Grado Usuario
            </label>
            <div class="col-md-6">
                <select class="form-control @error('grado') is-invalid @enderror" name="grado" id="grado" required>
                        <option value="" disabled selected>Selecciona Uno</option>
                    @foreach (App\Grado::all()->sortBy('id') as $grado)
                        <option value="{{$grado->id}}">{{$grado->id}}</option>
                    @endforeach
                </select>
                @error('grado')
                    <span class="help-block">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="nombre" class="col-md-4 col-form-label text-md-right">
                Nombre
            </label>
            <div class="col-md-6">
                <input id="nombre" type="text" class="form-control @error('nombre') is-invalid @enderror" name="nombre" value="{{ old('nombre') }}" required autofocus>

                @error('nombre')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="apellido_paterno" class="col-md-4 control-label text-md-right">Apellido Paterno</label>

            <div class="col-md-6">
                <input id="apellido_paterno" type="text" class="form-control @error('apellido_paterno') is-invalid @enderror" name="apellido_paterno" value="{{ old('apellido_paterno') }}" required>

                @error('apellido_paterno')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="apellido_materno" class="col-md-4 control-label text-md-right">Apellido Materno</label>

            <div class="col-md-6">
                <input id="apellido_materno" type="text" class="form-control @error('apellido_materno') is-invalid @enderror" name="apellido_materno" value="{{ old('apellido_materno') }}" required>

                @error('apellido_materno')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="email" class="col-md-4 col-form-label text-md-right">
                Correo
            </label>

            <div class="col-md-6">
                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="helpId" class="col-md-4 col-form-label text-md-right">Contraseña recomendada</label>
                <div class="col-md-6">
                    <strong> {{random_str()}}</strong>
                </div>
        </div>

        <div class="form-group row">
            <label for="password" class="col-md-4 col-form-label text-md-right">Contraseña</label>

            <div class="col-md-6">
                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                @error('password')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">@lang('strings.pass_confirm')</label>

            <div class="col-md-6">
                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    Registrar Usuario
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('page-scripts')
    <script src="{{ asset('js/warn-exit.js') }}" defer></script>
@endsection

@section('title')
    Actualizar Usuario - {{$user->nombre_completo}}
@endsection

@section('content')
    <form class="form-horizontal" method="POST" action="{{ route('users.update', $user->id) }}">
        @csrf
        @method('PATCH')
        <div class="form-group row">
            <label for="grado" class="col-md-4 col-form-label text-md-right">
                Grado Usuario
            </label>
            <div class="col-md-6">
                <select class="form-control @error('grado') is-invalid @enderror" name="grado" id="grado" required>
                    @foreach (App\Grado::all()->sortBy('id') as $grado)
                        <option value="{{$grado->id}}" @if ($grado->id == $user->grado) {{'selected'}} @endif>{{$grado->id}}</option>
                    @endforeach
                </select>
                @error('grado')
                    <span class="help-block">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="nombre" class="col-md-4 col-form-label text-md-right">
                Nombre
            </label>
            <div class="col-md-6">
                <input id="nombre" type="text" class="form-control @error('nombre') is-invalid @enderror" name="nombre" value="{{ $user->nombre }}" required autofocus>

                @error('nombre')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="apellido_paterno" class="col-md-4 control-label text-md-right">Apellido Paterno</label>

            <div class="col-md-6">
                <input id="apellido_paterno" type="text" class="form-control @error('apellido_paterno') is-invalid @enderror" name="apellido_paterno" value="{{ $user->apellido_paterno }}" required>

                @error('apellido_paterno')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="apellido_materno" class="col-md-4 control-label text-md-right">Apellido Materno</label>

            <div class="col-md-6">
                <input id="apellido_materno" type="text" class="form-control @error('apellido_materno') is-invalid @enderror" name="apellido_materno" value="{{  $user->apellido_materno }}" required>

                @error('apellido_materno')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="email" class="col-md-4 col-form-label text-md-right">
                Correo
            </label>

            <div class="col-md-6">
                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{$user->email}}" required autocomplete="email">

                @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4 text-md-right">
                <a class="btn btn-danger" role="button" href="{{route('users.index')}}">
                    <i class="fa fa-undo" aria-hidden="true"></i>
                    Regresar
                </a>
                <button type="submit" class="btn btn-primary">
                    Actualizar Usuario
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title')
    Usuarios
@endsection

@section('content')

<div class="row">
    <div class="col-md-12">
        @include('flash-message')
    </div>
</div>
@can('create', App\User::class)
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-primary" href="{{route('users.create')}}" role="button">
                <i class="fa fa-user-plus" aria-hidden="true"></i>
                <span class="">Registrar usuario</span>
            </a>
        </div>
    </div>
@endcan
<hr>

{{--
-- Barra de búsqueda aún no lista para implementación --
--}}
<div class="row">
    <div class="col-sm-12">
        {{$users->links()}}
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Grado</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Apellido Paterno</th>
                        <th scope="col">Apellido Materno</th>
                        <th scope="col">Correo</th>
                        <th scope="col">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($users as $user)
                        <tr>
                            <th scope="row">{{$user->id}}</td>
                            <td>{{$user->grado}}</td>
                            <td>{{$user->nombre}}</td>
                            <td>{{$user->apellido_paterno}}</td>
                            <td>{{$user->apellido_materno}}</td>
                            <td>{{$user->email}}</td>
                            <td>
                                <form action="{{ route('users.destroy',$user->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <div class="btn-group" role="group" aria-label="Modificar Usuario">
                                        <a name="veruser" href="{{route('users.show',$user->id)}}" role="button" class="btn btn-success">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <a name="editarUsuario" id="editarUsuario{{$user->id}}" class="btn btn-primary" href="{{route('users.edit', $user->id)}}" role="button" title="Editar">
                                            <i class="fas fa-edit" aria-hidden="true"></i>
                                        </a>
                                        <button type="submit" onclick="return confirm('¿Estás seguro de eliminar al usuario con nombre \'{{$user->nombre_completo}}?\'')" class="btn btn-danger" href="#" role="button" title="Eliminar">
                                            <i class="fas fa-trash" aria-hidden="true"></i>
                                        </button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        {{$users->links()}}
    </div>
</div>



@endsection