routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'CalendarioController@index');

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/calendario', 'CalendarioController@index')->name('calendario');

// -------- USUARIOS ---------
Auth::routes();
Route::resource('users', 'UsersController');
Route::get('/users/buscar/{consulta}', 'UsersController@buscar')->name('users.buscar');

// ----- DIVISIONES -------
Route::resource('divisions', 'DivisionController');
Route::get('/divisions/buscar/{consulta}', 'DivisionController@buscar')->name('divisions.buscar');

// ------- DEPARTAMENTOS -------
Route::resource('divisions.departamentos', 'DivisionDepartamentoController');
Route::resource('departamentos', 'DepartamentosController');

// ------- ACADEMIAS --------
Route::resource('divisions.departamentos.academias', 'DivisionDepartamentoAcademiaController');
Route::get('/divisions/{division}/departamentos/{departamento}/academias/{academia}/miembros/agregar', 'DivisionDepartamentoAcademiaController@agregarMiembro')
        ->name('divisions.departamentos.academias.agregar-miembro');
Route::delete('/divisions/{division}/departamentos/{departamento}/academias/{academia}/miembros/{miembro}', 'DivisionDepartamentoAcademiaController@darDeBajaMiembro')
        ->name('divisions.departamentos.academias.darDeBajaMiembro');

// ------ REUNIONES -----------
Route::resource('academias.reuniones', 'AcademiaReunionesController')
        ->except(['store', 'update', 'destroy'])
        ->middleware('auth');
Route::resource('/reuniones', 'ReunionesController')
        ->except(['store', 'update', 'destroy']);
Route::get('/reuniones/{id}/orden-del-dia', 'ReunionesController@descargarOrdenDelDia')
        ->name('reuniones.ordendeldia.descargar');
Route::get('/reuniones/{id}/emailpreview', 'ReunionesController@emailPreview');
// Route::get('/reuniones/{reunion}/vista-previa-od', function (App\Reunion $reunion){
//     $pdf = PDF::loadView('reuniones.ordendeldia', ['reunion' => $reunion]);
//     return $pdf->stream();
//     // return view('reuniones.ordendeldia', compact('reunion'));
// });

// --------- MINUTAS --------------
Route::resource('reuniones.minuta', 'ReunionesMinutasController')
        ->only(['index', 'create']);
// Route::get('/reuniones/{reunion}/minuta/vista-previa/', function (App\Reunion $reunion){
//     $pdf = PDF::loadView('reuniones.pdf.minuta', ['reunion' => $reunion]);
//     return $pdf->stream();
// });

// Enviar comentarios
Route::resource('feedback', 'FeedbackController')->only(['create', 'store'])->middleware('auth');

// ----------- TEAPOT ----------
Route::get('/teapot/brew','TeapotController@brew')->name('teapot.brew');

// TEST
// Route::view('mailtest', function () {
//         $feedback = App\Feedback::find(1);
//         return new App\Mail\FeedbackMail($feedback);
// });

app/Departamento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Departamento extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'division_id', 'nombre', 'url', 'logo'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    public function division()
    {
        return $this->belongsTo(Division::class);
    }

    public function jefes()
    {
        return $this->belongsToMany(User::class, 'departamento_jefe',
                                    'departamento_id', 'jefe_id')
                    ->using(DetallesIngresoEgreso::class)
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getJefeAttribute()
    {
        return $this->jefes()->wherePivot('fecha_egreso', '=', null)->first();
    }

    public function academias()
    {
        return $this->hasMany(Academia::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password',
        'grado', 'nombre',
        'apellido_paterno', 'apellido_materno'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Buscar usuario
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $busqueda
     * @param int $num_resultados
     * 
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeBuscar($query, string $busqueda, int $limit)
    {
        // $connection = config('database.default');
        // $driver = config("database.connections.{$connection}.driver");
        // if ($driver == 'sqlite') {
        //     $query = $query->whereRaw("nombre || ' ' || apellido_paterno || ' ' || apellido_materno LIKE '%{$busqueda}%'")
        //                 ->orderBy('apellido_paterno')
        // } else {
            $query = $query->whereRaw("CONCAT(nombre, ' ', apellido_paterno, ' ', apellido_materno) LIKE '%{$busqueda}%'")
                        ->orderBy('apellido_paterno');
        // }
        return $limit ? $query->limit($limit) : $query;
    }

    /**
     * Genera un api_token único y guarda al usuario.
     *
     * @return bool
     */
    public function rollApiKey(){
        do{
           $this->api_token = str_random(80);
        }while($this->where('api_token', $this->api_token)->exists());
        $this->save();
        return true;
    }

    /**
     * Retorna true si el usuario es miembro actual de la $academia dada.
     *
     * @param App\Academia $academia
     * @return bool
     */
    public function esMiembroActual(Academia $academia)
    {
        if ($academia->miembrosActuales->isEmpty()) return false;
        return $academia->miembrosActuales->contains($this); // Checa si hay registros donde el miembro siga activo
    }

    /**
     * Retorna true si el usuario es administrador del sistema.
     *
     * @return bool
     */
    public function getEsAdminAttribute()
    {
        return $this->email == config('admin.email');
    }

    /**
     * Retorna el nombre completo (iniciando por nombre) del usuario.
     *
     * @return string
     */
    public function getNombreCompletoAttribute()
    {
        return "{$this->nombre} {$this->apellido_paterno} {$this->apellido_materno}";
    }

    /**
     * Retorna el nombre completo (iniciando por nombre) con grado académico del usuario.
     *
     * @return string
     */
    public function getGradoNombreCompletoAttribute()
    {
        return "{$this->grado} {$this->nombre} {$this->apellido_paterno} {$this->apellido_materno}";
    }

    /* --------  Relaciones con tablas de jerarquía de la FI --------------- */

    public function divisionesQueHaDirigido()
    {
        return $this->belongsToMany(Division::class, 'division_jefe',
                                    'jefe_id', 'division_id')
                    ->using(DetallesIngresoEgreso::class)
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getDivisionesQueDirigeAttribute()
    {
        return $this->divisionesQueHaDirigido()->wherePivot('fecha_egreso', '=', null)->get();
    }

    public function departamentosQueHaDirigido()
    {
        return $this->belongsToMany(Departamento::class, 'departamento_jefe',
                                        'jefe_id', 'departamento_id')
                    ->using(DetallesIngresoEgreso::class)
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getDepartamentosQueDirigeAttribute()
    {
        return $this->departamentosQueHaDirigido()->wherePivot('fecha_egreso', '=', null)->get();
    }

    public function academiasQueHaPresidido()
    {
        return $this->belongsToMany(Academia::class, 'academia_presidente',
                                        'presidente_id', 'academia_id')
                    ->using(DetallesIngresoEgreso::class)
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getAcademiasQuePresideAttribute()
    {
        return $this->academiasQueHaPresidido()->wherePivot('fecha_egreso', '=', null)->get();
    }

    public function academias()
    {
        return $this->belongsToMany(Academia::class, 'academia_miembro',
                                    'miembro_id', 'academia_id')
                    ->using(DetallesIngresoEgreso::class) // Tabla pivote
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getAcademiasComoMiembroActivoAttribute()
    {
        return $this->academias()->wherePivot('fecha_egreso', '=', null)->get();
    }

    /* --------  Relaciones con tablas de reuniones, acuerdos, etc --------------- */

    public function reunionesComoConvocado()
    {
        return $this->belongsToMany(Reunion::class, 
            'convocado_reunion', 'convocado_id', 'reunion_id')
            ->as('asistencia')
            ->withPivot('asistio');
    }

    public function reunionesComoInvitadoExterno()
    {
        return $this->belongsToMany(Reunion::class, 
            'invitado_reunion', 'invitado_id', 'reunion_id')
            ->as('asistencia')
            ->withPivot('asistio');
    }
    
    public function getReunionesComoPresidenteAttribute()
    {
        return Reunion::whereIn('academia_id', $this->academiasQuePreside->pluck('id'))->get();
    }
    
    public function getReunionesComoJefeDeDepartamentoAttribute()
    {
        return Reunion::whereIn('academia_id', // Consulta principal (reuniones de las academias)
                Academia::whereIn('departamento_id', // Subconsulta 1 (academias del departamento)
                                $this->departamentosQueDirige->pluck('id') 
                            )->get()->pluck('id')
                        )->get();
    }
    
    public function getReunionesComoJefeDeDivisionAttribute()
    {
        return Reunion::whereIn('academia_id', // Consulta principal (reuniones de las academias)
                Academia::whereIn('departamento_id', // Subconsulta 1 (academias de departamentos que dirige)
                    Departamento::whereIn('division_id', // Subconsulta 2 (departamentos de divisiones que dirige)
                        $this->divisionesQueDirige->pluck('id') 
                    )->get()->pluck('id')
                )->get()->pluck('id')
            )->get();
    }

    public function getReunionesAttribute()
    {
        // Union entre todas las consultas
        return $this->reunionesComoConvocado->merge(
            $this->reunionesComoInvitadoExterno->merge(
                $this->ReunionesComoPresidente->merge(
                    $this->reunionesComoJefeDeDepartamento->merge(
                        $this->reunionesComoJefeDeDivision
                    )
                )
            )
        );
    }

    public function acuerdos()
    {
        return $this->hasMany(Acuerdo::class, 'responsable_id', 'id');
    }
}

app/Http/Controllers/DepartamentosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Departamento;

class DepartamentosController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departamentos = Departamento::paginate(10);
        return view('departamentos.index', compact('departamentos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Departamento::class);
        return view('departamentos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Departamento::class);
        $request->validate([
            'nombre' => 'required|unique:departamentos|max:50|string',
            'id_jefe_dpto' => 'required|exists:academicos,id',
            'division_id' => 'required|exists:divisions,id',
        ]);

        Departamento::create($request->all());

        return redirect()->route('departamentos.index')
                        ->with('success', 'Departamento con nombre \''
                                        . $request['nombre']
                                        .'\' creado satisfactoriamente.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Departamento $departamento)
    {
        $this->authorize('update', $departamento);
        return view('departamentos.edit', compact('departamento'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Departamento $departamento)
    {
        $this->authorize('update', $departamento);
        $request->validate([
            'nombre' => 'required|max:50|string',
            'id_jefe_dpto' => 'required|exists:academicos,id',
            'division_id' => 'required|exists:divisions,id',
        ]);

        $departamento->update($request->all());

        return redirect()->route('departamentos.index')
                        ->with('success', 'Departamento con nombre \''
                                        . $request['nombre']
                                        .'\' actualizado satisfactoriamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Departamento $departamento)
    {
        $this->authorize('delete', $departamento);
        if($departamento->academias->isEmpty()){ 
            $departamento->delete();
            return redirect()->route('departamentos.index')
                        ->with('success', 'Departamento borrado.');

        } else {
            return redirect()->route('departamentos.index')
                            ->with('error', 'No se puede eliminar un departamento que aún tiene academias.');
        }
    }

    public function buscar($busqueda)
    {
        $busqueda = urldecode($busqueda);
    
        $departamentos = Departamento::where('nombre', 'like', '%' . $busqueda . '%')
                            ->orderBy('nombre', 'desc')
                            ->limit(5)
                            ->get();
        
        return response()->json($departamentos);
    }
}

resources/views/departamentos/create.blade.php
@extends('layouts.app')

@section('title')
    Agregar Departamento
@endsection

@section('content')
    <form class="form-horizontal" method="POST" action="{{route('departamentos.index')}}">
        @csrf
        
        <buscar-division
            tiene-errores="{{$errors->has('division_id')}}"
            errores="{{$errors->has('division_id') ? $errors->first('division_id') : ''}}"
            busqueda-inicial=""
            input-tag-name="division_id"
            label-inicial="División de procedencia">
        </buscar-division>

        <div class="form-group row">
            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre del Departamento</label>

            <div class="col-md-6">
                <input id="nombre" type="text" class="form-control  @error('nombre') is-invalid @enderror" name="nombre" value="{{ old('nombre') }}" required>

                @error('nombre')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <buscar-usuario
            tiene-errores="{{$errors->has('id_jefe_dpto')}}"
            errores="{{$errors->has('id_jefe_dpto') ? $errors->first('id_jefe_dpto') : ''}}"
            busqueda-inicial=""
            input-tag-name="id_jefe_dpto"
            label-inicial="Jefe de departamento">
        </buscar-usuario>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    Añadir departamento
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/departamentos/edit.blade.php
@extends('layouts.app')

@section('title')
    Agregar Departamento
@endsection

@section('content')
    <form class="form-horizontal" method="POST" action="{{route('departamentos.update', $departamento->id)}}">
        @csrf
        @method('PATCH')

        <div style="@cannot('create', App\Departamento::class) {{'display: none'}} @endcannot">
            <buscar-division
                tiene-errores="{{$errors->has('division_id')}}"
                errores="{{$errors->has('division_id') ? $errors->first('division_id') : ''}}"
                busqueda-inicial="{{ $departamento->division->siglas }}"
                input-tag-name="division_id"
                label-inicial="División de procedencia">
            </buscar-division>
        </div>

        <div class="form-group row">
            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre Completo</label>

            <div class="col-md-6">
                <input id="nombre" type="text" class="form-control  @error('nombre') is-invalid @enderror" name="nombre" value="{{ $departamento->nombre }}" required>

                @error('nombre')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div style="@cannot('create', App\Departamento::class) {{'display: none'}} @endcannot">
            <buscar-usuario
                tiene-errores="{{$errors->has('id_jefe_dpto')}}"
                errores="{{$errors->has('id_jefe_dpto') ? $errors->first('id_jefe_dpto') : ''}}"
                busqueda-inicial="{{ $departamento->jefe->nombreCompleto() }}"
                input-tag-name="id_jefe_dpto"
                label-inicial="Jefe de Departamento">
            </buscar-usuario>
        </div>
        
        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4 text-md-right">
                <a class="btn btn-danger" role="button" href="{{route('departamentos.index')}}">
                    <i class="fa fa-undo" aria-hidden="true"></i>
                    Regresar
                </a>
                <button type="submit" class="btn btn-primary">
                    Actualizar Departamento
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/departamentos/index.blade.php
@extends('layouts.app')

@section('title')
    Departamentos
@endsection

@section('content')

<div class="row">
    <div class="col-sm-12">
        @include('flash-message')
    </div>
</div>

@can('create', App\Departamento::class)
    <div class="row">
        <div class="col-md-12 py-2">
            <a class="btn btn-primary" href="{{route('departamentos.create')}}" role="button">
                <i class="fa fa-plus" aria-hidden="true"></i>
                <span class="ml-2">Añadir departamento</span>
            </a>
        </div>
    </div>
@endcan

{{-- Barra de búsqueda próximamente aquí --}}

<hr>

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th scope="col">División</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Jefe</th>
                        {{-- @can('create', App\Academia::class) --}}                        
                            <th scope="col">Acciones</th>
                        {{-- @endcan --}}
                    </tr>
                </thead>
                <tbody>
                    @foreach ($departamentos as $departamento)
                        <tr>
                            <td>{{$departamento->division->siglas}}</td>
                            <td>{{$departamento->nombre}}</td>
                            <td>{{$departamento->jefe->grado_nombre_completo}}</td>
                            {{-- @can('create', App\Academia::class) --}}  
                                <td>
                                    <form action="{{ route('departamentos.destroy',$departamento->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <div class="btn-group" role="group" aria-label="Modificar departamento">
                                            @can('update', $departamento)
                                                <a name="editardepartamento" id="editardepartamento{{$departamento->id}}" class="btn btn-primary" href="{{route('departamentos.edit', $departamento->id)}}" role="button" title="Editar">
                                                    <i class="fas fa-edit" aria-hidden="true"></i>
                                                </a>
                                            @endcan
                                            @can('delete', $departamento)
                                                <button type="submit" onclick="return confirm('¿Estás seguro de eliminar \'{{$departamento->nombre}}?\'')" class="btn btn-danger" href="#" role="button" title="Eliminar">
                                                    <i class="fas fa-trash" aria-hidden="true"></i>
                                                </button>
                                            @endcan
                                            
                                        </div>
                                    </form>
                                </td>
                            {{-- @endcan --}}
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        {{$departamentos->links()}}
    </div>
</div>

@endsection

resources/views/departamentos/show.blade.php
@extends('layouts.app')

@section('title')
    {{$departamento->nombre}}
@endsection

@section('content')
    {{$departamento->nombre}}
@endsection