routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'CalendarioController@index');

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/calendario', 'CalendarioController@index')->name('calendario');

// -------- USUARIOS ---------
Auth::routes();
Route::resource('users', 'UsersController');
Route::get('/users/buscar/{consulta}', 'UsersController@buscar')->name('users.buscar');

// ----- DIVISIONES -------
Route::resource('divisions', 'DivisionController');
Route::get('/divisions/buscar/{consulta}', 'DivisionController@buscar')->name('divisions.buscar');

// ------- DEPARTAMENTOS -------
Route::resource('divisions.departamentos', 'DivisionDepartamentoController');
Route::resource('departamentos', 'DepartamentosController');

// ------- ACADEMIAS --------
Route::resource('divisions.departamentos.academias', 'DivisionDepartamentoAcademiaController');
Route::get('/divisions/{division}/departamentos/{departamento}/academias/{academia}/miembros/agregar', 'DivisionDepartamentoAcademiaController@agregarMiembro')
        ->name('divisions.departamentos.academias.agregar-miembro');
Route::delete('/divisions/{division}/departamentos/{departamento}/academias/{academia}/miembros/{miembro}', 'DivisionDepartamentoAcademiaController@darDeBajaMiembro')
        ->name('divisions.departamentos.academias.darDeBajaMiembro');

// ------ REUNIONES -----------
Route::resource('academias.reuniones', 'AcademiaReunionesController')
        ->except(['store', 'update', 'destroy'])
        ->middleware('auth');
Route::resource('/reuniones', 'ReunionesController')
        ->except(['store', 'update', 'destroy']);
Route::get('/reuniones/{id}/orden-del-dia', 'ReunionesController@descargarOrdenDelDia')
        ->name('reuniones.ordendeldia.descargar');
Route::get('/reuniones/{id}/emailpreview', 'ReunionesController@emailPreview');
// Route::get('/reuniones/{reunion}/vista-previa-od', function (App\Reunion $reunion){
//     $pdf = PDF::loadView('reuniones.ordendeldia', ['reunion' => $reunion]);
//     return $pdf->stream();
//     // return view('reuniones.ordendeldia', compact('reunion'));
// });

// --------- MINUTAS --------------
Route::resource('reuniones.minuta', 'ReunionesMinutasController')
        ->only(['index', 'create']);
// Route::get('/reuniones/{reunion}/minuta/vista-previa/', function (App\Reunion $reunion){
//     $pdf = PDF::loadView('reuniones.pdf.minuta', ['reunion' => $reunion]);
//     return $pdf->stream();
// });

// Enviar comentarios
Route::resource('feedback', 'FeedbackController')->only(['create', 'store'])->middleware('auth');

// ----------- TEAPOT ----------
Route::get('/teapot/brew','TeapotController@brew')->name('teapot.brew');

// TEST
// Route::view('mailtest', function () {
//         $feedback = App\Feedback::find(1);
//         return new App\Mail\FeedbackMail($feedback);
// });

app/Academia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Academia extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'nombre', 'departamento_id'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    public function departamento()
    {
        return $this->belongsTo(Departamento::class);
    }
    
    public function getDivisionAttribute()
    {
        return $this->departamento->division;
    }

    public function presidentes()
    {
        return $this->belongsToMany(User::class, 'academia_presidente',
                                    'academia_id', 'presidente_id')
                    ->using(DetallesIngresoEgreso::class)
                    ->withPivot('fecha_ingreso', 'fecha_egreso');;
    }

    public function getPresidenteAttribute()
    {
        return $this->presidentes()->wherePivot('fecha_egreso', '=', null)->first();
    }

    public function miembros()
    {
        return $this->belongsToMany(User::class, 'academia_miembro',
                                    'academia_id', 'miembro_id')
                    ->using(DetallesIngresoEgreso::class)    
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getMiembrosActualesAttribute()
    {
        return $this->miembros()
                    ->wherePivot('fecha_egreso', '=', null)
                    ->get()
                    ->sortBy(function ($miembro){
                        return nombre_completo($miembro, $ordenarPor = 'apellido');
                    });
    }

    public function getMiembrosActivosAttribute()
    {
        return $this->miembros()
                    ->wherePivot('activo', '=', null)
                    ->get()
                    ->sortBy(function ($miembro){
                        return nombre_completo($miembro, $ordenarPor = 'apellido');
                    });
    }

    public function reuniones()
    {
        return $this->hasMany(Reunion::class);
    }

    public function getAcuerdosPendientesAttribute()
    {
        $temas_reuniones_ids = $this->temas->pluck('id');
        return Acuerdo::pendientes()->whereIn('tema_id', $temas_reuniones_ids)->get();
    }

    public function temas()
    {
        return $this->hasManyThrough(Tema::class, Reunion::class);
    }

    /**
     * Acuerdos que tiene esta academia. Cuando el $estado_fin es 'pend', la función 
     * retornará sólo acuerdos pendientes. Cuando $estado_fin es 'fin', retornará 
     * únicamente acuerdos finalizados. En cualquier otro caso, la función retornará tanto
     * acuerdos finalizados como los pendientes.
     * 
     * @param string $estado_fin 
     * @return Illuminate\Database\Eloquent\Collection
     */
    public function acuerdos(string $estado_fin = null)
    {
        $temas_reuniones_ids = $this->temas->pluck('id');
        $query = Acuerdo::whereIn('tema_id', $temas_reuniones_ids);
        if($estado_fin == 'pend') $query = $query->pendientes();
        else if($estado_fin == 'fin') $query = $query->finalizados();
        return $query->get();
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'password',
        'grado', 'nombre',
        'apellido_paterno', 'apellido_materno'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Buscar usuario
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param string $busqueda
     * @param int $num_resultados
     * 
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeBuscar($query, string $busqueda, int $limit)
    {
        // $connection = config('database.default');
        // $driver = config("database.connections.{$connection}.driver");
        // if ($driver == 'sqlite') {
        //     $query = $query->whereRaw("nombre || ' ' || apellido_paterno || ' ' || apellido_materno LIKE '%{$busqueda}%'")
        //                 ->orderBy('apellido_paterno')
        // } else {
            $query = $query->whereRaw("CONCAT(nombre, ' ', apellido_paterno, ' ', apellido_materno) LIKE '%{$busqueda}%'")
                        ->orderBy('apellido_paterno');
        // }
        return $limit ? $query->limit($limit) : $query;
    }

    /**
     * Genera un api_token único y guarda al usuario.
     *
     * @return bool
     */
    public function rollApiKey(){
        do{
           $this->api_token = str_random(80);
        }while($this->where('api_token', $this->api_token)->exists());
        $this->save();
        return true;
    }

    /**
     * Retorna true si el usuario es miembro actual de la $academia dada.
     *
     * @param App\Academia $academia
     * @return bool
     */
    public function esMiembroActual(Academia $academia)
    {
        if ($academia->miembrosActuales->isEmpty()) return false;
        return $academia->miembrosActuales->contains($this); // Checa si hay registros donde el miembro siga activo
    }

    /**
     * Retorna true si el usuario es administrador del sistema.
     *
     * @return bool
     */
    public function getEsAdminAttribute()
    {
        return $this->email == config('admin.email');
    }

    /**
     * Retorna el nombre completo (iniciando por nombre) del usuario.
     *
     * @return string
     */
    public function getNombreCompletoAttribute()
    {
        return "{$this->nombre} {$this->apellido_paterno} {$this->apellido_materno}";
    }

    /**
     * Retorna el nombre completo (iniciando por nombre) con grado académico del usuario.
     *
     * @return string
     */
    public function getGradoNombreCompletoAttribute()
    {
        return "{$this->grado} {$this->nombre} {$this->apellido_paterno} {$this->apellido_materno}";
    }

    /* --------  Relaciones con tablas de jerarquía de la FI --------------- */

    public function divisionesQueHaDirigido()
    {
        return $this->belongsToMany(Division::class, 'division_jefe',
                                    'jefe_id', 'division_id')
                    ->using(DetallesIngresoEgreso::class)
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getDivisionesQueDirigeAttribute()
    {
        return $this->divisionesQueHaDirigido()->wherePivot('fecha_egreso', '=', null)->get();
    }

    public function departamentosQueHaDirigido()
    {
        return $this->belongsToMany(Departamento::class, 'departamento_jefe',
                                        'jefe_id', 'departamento_id')
                    ->using(DetallesIngresoEgreso::class)
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getDepartamentosQueDirigeAttribute()
    {
        return $this->departamentosQueHaDirigido()->wherePivot('fecha_egreso', '=', null)->get();
    }

    public function academiasQueHaPresidido()
    {
        return $this->belongsToMany(Academia::class, 'academia_presidente',
                                        'presidente_id', 'academia_id')
                    ->using(DetallesIngresoEgreso::class)
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getAcademiasQuePresideAttribute()
    {
        return $this->academiasQueHaPresidido()->wherePivot('fecha_egreso', '=', null)->get();
    }

    public function academias()
    {
        return $this->belongsToMany(Academia::class, 'academia_miembro',
                                    'miembro_id', 'academia_id')
                    ->using(DetallesIngresoEgreso::class) // Tabla pivote
                    ->withPivot('fecha_ingreso', 'fecha_egreso');
    }

    public function getAcademiasComoMiembroActivoAttribute()
    {
        return $this->academias()->wherePivot('fecha_egreso', '=', null)->get();
    }

    /* --------  Relaciones con tablas de reuniones, acuerdos, etc --------------- */

    public function reunionesComoConvocado()
    {
        return $this->belongsToMany(Reunion::class, 
            'convocado_reunion', 'convocado_id', 'reunion_id')
            ->as('asistencia')
            ->withPivot('asistio');
    }

    public function reunionesComoInvitadoExterno()
    {
        return $this->belongsToMany(Reunion::class, 
            'invitado_reunion', 'invitado_id', 'reunion_id')
            ->as('asistencia')
            ->withPivot('asistio');
    }
    
    public function getReunionesComoPresidenteAttribute()
    {
        return Reunion::whereIn('academia_id', $this->academiasQuePreside->pluck('id'))->get();
    }
    
    public function getReunionesComoJefeDeDepartamentoAttribute()
    {
        return Reunion::whereIn('academia_id', // Consulta principal (reuniones de las academias)
                Academia::whereIn('departamento_id', // Subconsulta 1 (academias del departamento)
                                $this->departamentosQueDirige->pluck('id') 
                            )->get()->pluck('id')
                        )->get();
    }
    
    public function getReunionesComoJefeDeDivisionAttribute()
    {
        return Reunion::whereIn('academia_id', // Consulta principal (reuniones de las academias)
                Academia::whereIn('departamento_id', // Subconsulta 1 (academias de departamentos que dirige)
                    Departamento::whereIn('division_id', // Subconsulta 2 (departamentos de divisiones que dirige)
                        $this->divisionesQueDirige->pluck('id') 
                    )->get()->pluck('id')
                )->get()->pluck('id')
            )->get();
    }

    public function getReunionesAttribute()
    {
        // Union entre todas las consultas
        return $this->reunionesComoConvocado->merge(
            $this->reunionesComoInvitadoExterno->merge(
                $this->ReunionesComoPresidente->merge(
                    $this->reunionesComoJefeDeDepartamento->merge(
                        $this->reunionesComoJefeDeDivision
                    )
                )
            )
        );
    }

    public function acuerdos()
    {
        return $this->hasMany(Acuerdo::class, 'responsable_id', 'id');
    }
}

app/Http/Controllers/Api/DivisionController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Validation\Validator;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Division;
use App\Http\Resources\DivisionResource;
use App\Http\Resources\DivisionsCollection;

class DivisionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $divisiones = Division::all();
        return new DivisionsCollection($divisiones);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', Division::class);
        /*
        $data = $request->all();
        $validator = Validator::make($data, [
            [
                'siglas' => 'required|unique:divisions|max:10|string',
                'nombre' => 'required|unique:divisions|max:50|string',
                'url' => 'required|max:128|url',
                'fecha_ingreso' => 'max:128|date|before:'.Carbon::now(),
                'id_jefe_div' => 'required|exists:users,id',
            ]
        ]);
        */
        $data = request()->validate(
            [
                'siglas' => 'required|unique:divisions|max:10|string',
                'nombre' => 'required|unique:divisions|max:50|string',
                'url' => 'required|max:128|url',
                'fecha_ingreso' => 'max:128|date|before:'.Carbon::now(),
                'id_jefe_div' => 'required|exists:users,id',
            ]
        );

        $division = Division::create([
            'siglas' => $data['siglas'],
            'nombre' => $data['nombre'],
            'url' => $data['url'],
        ]);

        $division->jefes()->attach($data['id_jefe_div'], ['fecha_ingreso' => $data['fecha_ingreso']]);
        return new DivisionResource($division);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $division = Division::findOrFail($id);
        return response()->json($division);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return response()->json(['Nombre de la página' => "Editar division {$id}"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function buscar($consulta)
    {
        $consulta = urldecode($consulta);
        $divisiones = Division::where('nombre', 'like', '%' . $consulta . '%')
                            ->orWhere('siglas', 'like', '%' . $consulta . '%')
                            ->orderBy('nombre', 'desc')
                            ->limit(5)
                            ->get();

        return new DivisionResource($divisiones);
    }
}

resources/views/divisions/departamentos/create.blade.php
@extends('layouts.app')

@section('title')
    Agregar Departamento para la {{$division->nombre}}
@endsection

@section('content')
    <form class="form-horizontal" method="POST" action="{{route('divisions.departamentos.index', compact('division'))}}">
        @csrf

        <div class="form-group row">
            <label for="nombre" class="col-md-4 col-form-label text-md-right">Nombre del Departamento</label>
            
            <div class="col-md-6">
                <div class="input-group">
                    <div class="input-group-append">
                      <span class="input-group-text">Departamento de </span>
                    </div>
                    <input id="nombre" type="text" class="form-control  @error('nombre') is-invalid @enderror" name="nombre" value="{{ old('nombre') }}" required>
                    @error('nombre')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
            </div>
        </div>

        <hr>

        <buscar-usuario
            tiene-errores="{{$errors->has('id_jefe_dpto')}}"
            errores="{{$errors->has('id_jefe_dpto') ? $errors->first('id_jefe_dpto') : ''}}"
            busqueda-inicial=""
            input-tag-name="id_jefe_dpto"
            label-inicial="Jefe de departamento">
        </buscar-usuario>

        <div class="form-group row">
            <label for="fecha_ingreso" class="col-md-4 col-form-label text-md-right">Fecha de inicio de su cargo</label>
            <div class="col-md-6">
                <input id="fecha_ingreso" type="date" class="form-control  @error('fecha_ingreso') is-invalid @enderror" name="fecha_ingreso" value="{{ old('fecha_ingreso') }}" required>

                @error('fecha_ingreso')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    Añadir departamento
                </button>
            </div>
        </div>
    </form>
@endsection

resources/views/divisions/departamentos/index.blade.php
@extends('layouts.app')

@section('title')
    Departamentos de la {{$division->nombre}}
@endsection

@section('content')

<div class="row">
    <div class="col-sm-12">
        @include('flash-message')
    </div>
</div>

@can('create', App\Departamento::class)
    <div class="row">
        <div class="col-md-12 py-2">
            <a class="btn btn-primary" href="{{route('divisions.departamentos.create', $division->id)}}" role="button">
                <i class="fa fa-plus" aria-hidden="true"></i>
                <span class="ml-2">Añadir departamento</span>
            </a>
        </div>
    </div>
@endcan

{{-- Barra de búsqueda próximamente aquí --}}

<hr>

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Jefe</th>
                        {{-- @can('create', App\Academia::class) --}}
                            <th scope="col">Acciones</th>
                        {{-- @endcan --}}
                    </tr>
                </thead>
                <tbody>
                    @foreach ($division->departamentos as $departamento)
                        <tr>
                            <td>{{$departamento->nombre}}</td>
                            <td>{{'placeholder-jefe'/*$departamento->jefe->grado_nombre_completo*/}}</td>
                            {{-- @can('create', App\Academia::class) --}}
                                <td>
                                    <form action="{{ route('departamentos.destroy',$departamento->id) }}" method="POST">
                                        <div class="btn-group" role="group" aria-label="Modificar departamento">
                                            <a name="verdepartamento" href="{{route('departamentos.show',$departamento->id)}}" role="button" class="btn btn-success">
                                                <i class="fas fa-eye"></i>
                                            </a>
                                            @can('update', $departamento)
                                                <a name="editardepartamento" id="editardepartamento{{$departamento->id}}" class="btn btn-primary" href="{{route('departamentos.edit', $departamento->id)}}" role="button" title="Editar">
                                                    <i class="fas fa-edit" aria-hidden="true"></i>
                                                </a>
                                            @endcan
                                            @can('delete', $departamento)
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" onclick="return confirm('¿Estás seguro de eliminar \'{{$departamento->nombre}}?\'')" class="btn btn-danger" href="#" role="button" title="Eliminar">
                                                    <i class="fas fa-trash" aria-hidden="true"></i>
                                                </button>
                                            @endcan

                                        </div>
                                    </form>
                                </td>
                            {{-- @endcan --}}
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

{{-- <div class="row">
    <div class="col-sm-12">
        {{$departamentos->links()}}
    </div>
</div> --}}

@endsection

resources/views/divisions/departamentos/show.blade.php
@extends('layouts.app')

@section('title')
    Departamento de {{$departamento->nombre}}
@endsection

@section('content')
<div class="row">
    <div class="col-xs-12 col-md-8">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <td scope="row">Nombre del Departamento</td>
                    <td>{{$departamento->nombre}}</td>
                </tr>
                <tr>
                    <td scope="row">Jefe de Departamento</td>
                    <td>{{$departamento->jefe->grado_nombre_completo}}</td>
                </tr>
                <td scope="row">Correo</td>
                    <td>
                        <a href="mailto:{{ $departamento->jefe->email }}">
                            {{ $departamento->jefe->email }}
                        </a>
                    </td>
                <tr>
                    <td scope="row">División de origen</td>
                    <td>
                        <a href="{{route('divisions.show', $division->id)}}">{{$division->nombre}}</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col-md-12 pb-2">
        <h5>
            Academias
        </h5>
    </div>
</div>
@can('create', App\Academia::class)
    <div class="row">
        <div class="col-md-12 py-2">
            <a class="btn btn-primary" href="{{route('divisions.departamentos.academias.create', [$division->id, $departamento->id])}}" role="button">
                <i class="fa fa-plus" aria-hidden="true"></i>
                <span class="ml-2">Añadir academia</span>
            </a>
        </div>
    </div>
@endcan

{{-- Barra de búsqueda próximamente aquí --}}

<hr>
<div class="row">
    <div class="col-md-12">
        @include('flash-message')
    </div>
</div>
@if ($departamento->academias->isEmpty())
    <div class="row">
        <div class="col-sm-12">
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <strong>Este departamento no tiene academias registradas</strong>
            </div>
        </div>
    </div>
@else
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Academia</th>
                            <th scope="col">Presidente</th>
                            {{-- @can('create', App\Academia::class) --}}
                                <th scope="col">Acciones</th>
                            {{-- @endcan --}}
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($departamento->academias as $academia)
                            <tr>
                                <td>{{$academia->nombre}}</td>
                                <td>{{$academia->presidente->gradoNombreCompleto}}</td>
                                {{-- @can('create', App\Academia::class) --}}
                                    <td>
                                        <form action="{{ route('divisions.departamentos.academias.destroy', [$division->id, $departamento->id, $academia->id]) }}" method="POST">
                                            <div class="btn-group" role="group" aria-label="Modificar academia">
                                                <a name="veracademia" href="{{route('divisions.departamentos.academias.show', [$division->id, $departamento->id, $academia->id])}}" role="button" class="btn btn-success">
                                                    <i class="fas fa-eye"></i>
                                                </a>
                                                @can('update', $academia)
                                                    <a name="editaracademia" id="editaracademia{{$academia->id}}" class="btn btn-primary" href="{{route('divisions.departamentos.academias.edit', [$division->id, $departamento->id, $academia->id])}}" role="button" title="Editar">
                                                        <i class="fas fa-edit" aria-hidden="true"></i>
                                                    </a>
                                                @endcan
                                                @can('delete', $academia)
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" onclick="return confirm('¿Estás seguro de eliminar la Academia de {{$academia->nombre}}?')" class="btn btn-danger" href="#" role="button" title="Eliminar">
                                                        <i class="fas fa-trash" aria-hidden="true"></i>
                                                    </button>
                                                @endcan

                                            </div>
                                        </form>
                                    </td>
                                {{-- @endcan --}}
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endif
@endsection